import { dirname, join } from "node:path";

type LockEntry = [string, string, { dependencies?: Record<string, string>; peerDependencies?: Record<string, string>; optionalPeers?: string[] }?];
type PackageMeta = { name?: string; version?: string; license?: string | { type?: string }; homepage?: string; repository?: string | { url?: string } };

const root = import.meta.dir;
const lockText = await Bun.file(join(root, "bun.lock")).text();
const lock = JSON.parse(lockText.replace(/,\s*([}\]])/g, "$1"));
const roots = Object.keys(lock.workspaces[""].dependencies) as string[];
const packages = lock.packages as Record<string, LockEntry>;
const findKey = (name: string) => packages[name] ? name : Object.keys(packages).find((key) => key.endsWith(`/${name}`));
const seen = new Set<string>();
const visit = (name: string) => {
  const key = findKey(name);
  if (!key || seen.has(key)) return;
  seen.add(key);
  const spec = packages[key][2] ?? {};
  for (const dependency of Object.keys(spec.dependencies ?? {})) visit(dependency);
  for (const dependency of Object.keys(spec.peerDependencies ?? {})) {
    if (!(spec.optionalPeers ?? []).includes(dependency)) visit(dependency);
  }
};
for (const rootPackage of roots) visit(rootPackage);

const packageDir = (name: string) => join(root, "node_modules", ...name.split("/"));
const cleanRepository = (value?: string | { url?: string }) => {
  const raw = typeof value === "string" ? value : value?.url;
  const cleaned = raw?.replace(/^git\+/, "").replace(/\.git$/, "") ?? "";
  return /^[\w.-]+\/[\w.-]+(?:#.*)?$/.test(cleaned) ? `https://github.com/${cleaned}` : cleaned;
};
const records = await Promise.all([...seen].map(async (key) => {
  const [resolved] = packages[key];
  const at = resolved.lastIndexOf("@");
  const lockName = resolved.slice(0, at);
  const lockVersion = resolved.slice(at + 1);
  const meta = await Bun.file(join(packageDir(lockName), "package.json")).json() as PackageMeta;
  const license = typeof meta.license === "string" ? meta.license : meta.license?.type;
  if (!license) throw new Error(`Missing license metadata for ${lockName}`);
  const projectUrl = meta.homepage || cleanRepository(meta.repository) || `https://www.npmjs.com/package/${encodeURIComponent(lockName)}`;
  return { name: meta.name ?? lockName, version: meta.version ?? lockVersion, license, projectUrl };
}));
records.sort((a, b) => a.name.localeCompare(b.name));
const source = `// GENERATED by generate-oss-licenses.ts from bun.lock's production dependency closure\n// and installed package metadata. Do not edit manually; run bun run build.\nexport type OssLicense = { name: string; version: string; license: string; projectUrl: string };\nexport const ossLicenseProvenance = "bun.lock production dependency closure + installed package metadata";\nexport const ossLicenses: readonly OssLicense[] = ${JSON.stringify(records, null, 2)};\n`;
await Bun.write(join(root, "src/oss-licenses.ts"), source);
console.log(`src/oss-licenses.ts ${records.length} production packages`);
