import { expect, test } from "bun:test";
import {
  svgFigureA11y,
  tableCellProps,
  themeToggleProps,
} from "./src/report-runtime-semantics";

const read = (path: string) => Bun.file(`${import.meta.dir}/${path}`).text();

test("GFM table cells preserve alignment and identify column headers", async () => {
  expect(tableCellProps("center", true)).toEqual({
    style: { textAlign: "center" },
    scope: "col",
  });
  expect(tableCellProps("right", false)).toEqual({
    style: { textAlign: "right" },
  });
  expect(tableCellProps(null, false)).toEqual({});

  const runtime = await read("src/report-runtime.esm.ts");
  expect(runtime).toContain(
    "tableCellProps(node.align?.[cellKey], Cell === \"th\")",
  );
});

test("theme toggle exposes its current state and next action", () => {
  expect(themeToggleProps(false)).toEqual({
    label: "다크 모드로 전환",
    "aria-label": "다크 모드로 전환",
    "aria-pressed": false,
  });
  expect(themeToggleProps(true)).toEqual({
    label: "라이트 모드로 전환",
    "aria-label": "라이트 모드로 전환",
    "aria-pressed": true,
  });
});

test("report CSS sets relaxed reading rhythm and a conservative print baseline", async () => {
  const css = await read("src/report-runtime.css");
  expect(css).toMatch(/main\s*{[^}]*line-height:\s*1\.65;/s);

  const print = css.match(/@media print\s*{([\s\S]*)}\s*$/)?.[1] ?? "";
  expect(print).toMatch(/\.report-theme-control\s*{[^}]*display:\s*none !important;/s);
  expect(print).toMatch(/main\.report-document\s*{[^}]*padding:\s*0;/s);
  expect(print).toContain("--mantine-color-body: #fff;");
  expect(print).toContain("--mantine-color-text: #000;");
  expect(print).toMatch(/tr,[^}]*break-inside:\s*avoid;/s);
  expect(print).toMatch(/figure,[^}]*break-inside:\s*avoid;/s);
  expect(print).toContain(".mantine-Card-root");
});


test("static SVG figure contract is accessible, sanitized and dependency-free", async () => {
  expect(svgFigureA11y("request-path", "Request path", "Request traverses edge")).toEqual({
    role: "img",
    "aria-labelledby": "request-path-title request-path-description",
  });
  expect(() => svgFigureA11y("bad id", "Diagram")).toThrow();
  expect(() => svgFigureA11y("diagram", " ")).toThrow();
  const runtime = await read("src/report-runtime.esm.ts");
  expect(runtime).toContain("function SvgFigure");
  expect(runtime).toContain("new DOMParser()");
  expect(runtime).toContain("contains an external reference");
  expect(runtime).toContain('"marker-start", "marker-mid", "marker-end"');
  expect(runtime).toContain("defaultComponents: ComponentRegistry = { ThemeToggle, SvgFigure, OssLicenseFooter }");
  expect(runtime).not.toMatch(/from ["']mermaid["']/);
});

test("license popover describes scope, complete generated closure, and avoids duplication", async () => {
  const inventory = await read("src/oss-licenses.ts");
  const runtime = await read("src/report-runtime.esm.ts");
  expect(inventory).toContain("GENERATED by generate-oss-licenses.ts");
  expect(inventory.match(/\"name\":/g)?.length).toBeGreaterThan(100);
  const generator = await read("generate-oss-licenses.ts");
  expect(generator).toContain('lock.workspaces[""].dependencies');
  expect(generator).toContain("spec.dependencies");
  expect(generator).toContain("spec.peerDependencies");
  expect(inventory).toContain('"name": "react"');
  expect(inventory).toContain('"name": "@floating-ui/react"');
  expect(inventory).toContain('"name": "@fontsource/ibm-plex-sans-kr"');
  expect(inventory).toContain('"license": "OFL-1.1"');
  expect(runtime).toContain("Popover.Target");
  expect(runtime).toContain("Popover.Dropdown");
  expect(runtime).toContain("complete production dependency closure resolved from bun.lock");
  expect(runtime).toContain('appendLicenseFooter: !containsComponent(tree, "OssLicenseFooter")');
  expect(runtime).toContain('mdxProps(node).source === "diagram-design"');
  expect(runtime).toContain("mergeLicenses(documentLicenses, hasDiagramDesignFigure(tree))");
  expect(runtime).toContain("Document license projectUrl must be an HTTPS URL");
  expect(runtime).toContain('name: "diagram-design"');
  expect(runtime).toContain('version: "2.3.1"');
  expect(runtime).toContain("noopener noreferrer");
});

test("diagram and footer CSS is responsive, printable and motion-safe", async () => {
  const css = await read("src/report-runtime.css");
  expect(css).toMatch(/\.report-svg-canvas svg\s*{[^}]*width:\s*100%;[^}]*height:\s*auto;/s);
  expect(css).toContain("@media (max-width: 32rem)");
  expect(css).toContain("@media (prefers-reduced-motion: reduce)");
  const print = css.match(/@media print\s*{([\s\S]*)}\s*$/)?.[1] ?? "";
  expect(print).toContain("figure");
});


test("document provenance is opt-in, string-only, merged and deduplicated", async () => {
  const runtime = await read("src/report-runtime.esm.ts");
  expect(runtime).toContain("documentLicenses?: readonly DocumentLicense[]");
  expect(runtime).toContain("normalizeDocumentLicenses");
  expect(runtime).toContain("new Map(normalized.map");
  expect(runtime).toContain("hasDiagramDesignFigure");
  expect(runtime).not.toContain('node.name === "SvgFigure" && !');
  const readme = await read("README.md");
  expect(readme).toContain('source="diagram-design"');
  expect(readme).toContain("ordinary hand-authored SVG must not produce a false notice");
  expect(readme).toContain("every field is inert text");
});
