import { expect, test } from "bun:test";
import {
  svgFigureA11y,
  tableCellProps,
  themeToggleProps,
} from "./src/report-runtime-semantics";

const read = (path: string) => Bun.file(`${import.meta.dir}/${path}`).text();

test("GFM table cells preserve alignment and identify column headers", async () => {
  expect(tableCellProps("center", true)).toEqual({
    style: { textAlign: "center" },
    scope: "col",
  });
  expect(tableCellProps("right", false)).toEqual({
    style: { textAlign: "right" },
  });
  expect(tableCellProps(null, false)).toEqual({});

  const runtime = await read("src/report-runtime.esm.ts");
  expect(runtime).toContain(
    "tableCellProps(node.align?.[cellKey], Cell === \"th\")",
  );
});

test("theme toggle exposes its current state and next action", () => {
  expect(themeToggleProps(false)).toEqual({
    label: "다크 모드로 전환",
    "aria-label": "다크 모드로 전환",
    "aria-pressed": false,
  });
  expect(themeToggleProps(true)).toEqual({
    label: "라이트 모드로 전환",
    "aria-label": "라이트 모드로 전환",
    "aria-pressed": true,
  });
});

test("report CSS sets relaxed reading rhythm and a conservative print baseline", async () => {
  const css = await read("src/report-runtime.css");
  expect(css).toMatch(/main\s*{[^}]*line-height:\s*1\.65;/s);

  const print = css.match(/@media print\s*{([\s\S]*)}\s*$/)?.[1] ?? "";
  expect(print).toMatch(/\.report-theme-control\s*{[^}]*display:\s*none !important;/s);
  expect(print).toMatch(/main\.report-document\s*{[^}]*padding:\s*0;/s);
  expect(print).toContain("--mantine-color-body: #fff;");
  expect(print).toContain("--mantine-color-text: #000;");
  expect(print).toMatch(/tr,[^}]*break-inside:\s*avoid;/s);
  expect(print).toMatch(/figure,[^}]*break-inside:\s*avoid;/s);
  expect(print).toContain(".mantine-Card-root");
});



test("dimmed text meets WCAG AA contrast in light and dark themes", async () => {
  const css = await read("src/report-runtime.css");
  const dimmed = (scheme: "light" | "dark") =>
    css.match(new RegExp(`html\\[data-mantine-color-scheme="${scheme}"\\]\\s*\\{[^}]*--mantine-color-dimmed:\\s*(#[0-9a-f]{6})`, "i"))?.[1];
  const luminance = (hex: string) => {
    const channels = hex.slice(1).match(/../g)!.map((part) => parseInt(part, 16) / 255)
      .map((value) => value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4);
    return 0.2126 * channels[0] + 0.7152 * channels[1] + 0.0722 * channels[2];
  };
  const contrast = (foreground: string, background: string) => {
    const [lighter, darker] = [luminance(foreground), luminance(background)].sort((a, b) => b - a);
    return (lighter + 0.05) / (darker + 0.05);
  };

  expect(dimmed("light")).toBe("#6b737b");
  expect(dimmed("dark")).toBe("#929292");
  expect(contrast(dimmed("light")!, "#ffffff")).toBeGreaterThanOrEqual(4.5);
  expect(contrast(dimmed("dark")!, "#242424")).toBeGreaterThanOrEqual(4.5);
});

test("report CSS keeps tables compact and inline code subtly distinct", async () => {
  const css = await read("src/report-runtime.css");
  expect(css).toMatch(/table\s*{[^}]*font-size:\s*0\.9rem;[^}]*line-height:\s*1\.55;/s);
  expect(css).toMatch(
    /code:not\(pre code\)\s*{[^}]*padding:\s*0\.08em 0\.28em;[^}]*border-radius:\s*0\.25em;[^}]*background:\s*color-mix\(in srgb, currentColor 6%, transparent\);/s,
  );
  expect(css).not.toMatch(/(?:^|[,\s])pre code\s*{/m);
});

test("static SVG figure contract is accessible, sanitized and dependency-free", async () => {
  expect(svgFigureA11y("request-path", "Request path", "Request traverses edge")).toEqual({
    role: "img",
    "aria-labelledby": "request-path-title request-path-description",
  });
  expect(() => svgFigureA11y("bad id", "Diagram")).toThrow();
  expect(() => svgFigureA11y("diagram", " ")).toThrow();
  const runtime = await read("src/report-runtime.esm.ts");
  expect(runtime).toContain("function SvgFigure");
  expect(runtime).toContain("new DOMParser()");
  expect(runtime).toContain("document.createElementNS(svgNamespace, element.localName)");
  expect(runtime).toContain('document.createElementNS(svgNamespace, "title")');
  expect(runtime).toContain("return safeSvg;");
  expect(runtime).not.toContain("document.importNode(svg, true)");
  expect(runtime).toContain("contains an external reference");
  expect(runtime).toContain('"marker-start", "marker-mid", "marker-end"');
  expect(runtime).toContain("defaultComponents: ComponentRegistry = { ThemeToggle, SvgFigure, OssLicenseFooter }");
  expect(runtime).not.toMatch(/from ["']mermaid["']/);
});

test("license popover describes scope, complete generated closure, and avoids duplication", async () => {
  const inventory = await read("src/oss-licenses.ts");
  const runtime = await read("src/report-runtime.esm.ts");
  expect(inventory).toContain("GENERATED by generate-oss-licenses.ts");
  expect(inventory.match(/\"name\":/g)?.length).toBeGreaterThan(100);
  const generator = await read("generate-oss-licenses.ts");
  expect(generator).toContain('lock.workspaces[""].dependencies');
  expect(generator).toContain("spec.dependencies");
  expect(generator).toContain("spec.peerDependencies");
  expect(inventory).toContain('"name": "react"');
  expect(inventory).toContain('"name": "@floating-ui/react"');
  expect(inventory).toContain('"name": "@fontsource/ibm-plex-sans-kr"');
  expect(inventory).toContain('"license": "OFL-1.1"');
  expect(runtime).toContain("Popover.Target");
  expect(runtime).toContain("Popover.Dropdown");
  expect(runtime).toContain("complete production dependency closure resolved from bun.lock");
  expect(runtime).toContain('appendLicenseFooter: !containsComponent(tree, "OssLicenseFooter")');
  expect(runtime).toContain('mdxProps(node).source === "diagram-design"');
  expect(runtime).toContain("mergeLicenses(documentLicenses, hasDiagramDesignFigure(tree))");
  expect(runtime).toContain("Document license projectUrl must be an HTTPS URL");
  expect(runtime).toContain('name: "diagram-design"');
  expect(runtime).toContain('version: "2.3.1"');
  expect(runtime).toContain("noopener noreferrer");
});

test("diagram and footer CSS is responsive, printable and motion-safe", async () => {
  const css = await read("src/report-runtime.css");
  expect(css).toMatch(/\.report-svg-canvas svg\s*{[^}]*width:\s*100%;[^}]*height:\s*auto;/s);
  expect(css).toContain("@media (max-width: 32rem)");
  expect(css).toContain("@media (prefers-reduced-motion: reduce)");
  const print = css.match(/@media print\s*{([\s\S]*)}\s*$/)?.[1] ?? "";
  expect(print).toContain("figure");
});


test("document provenance is opt-in, string-only, merged and deduplicated", async () => {
  const runtime = await read("src/report-runtime.esm.ts");
  expect(runtime).toContain("documentLicenses?: readonly DocumentLicense[]");
  expect(runtime).toContain("normalizeDocumentLicenses");
  expect(runtime).toContain("new Map(normalized.map");
  expect(runtime).toContain("hasDiagramDesignFigure");
  expect(runtime).not.toContain('node.name === "SvgFigure" && !');
  const readme = await read("README.md");
  expect(readme).toContain('source="diagram-design"');
  expect(readme).toContain("ordinary hand-authored SVG must not produce a false notice");
  expect(readme).toContain("every field is inert text");
});


test("SVG figures retain namespaces and geometry in a real browser", async () => {
  const chrome = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
  if (!(await Bun.file(chrome).exists())) return;
  const page = new URL("./examples/svg-namespace-test.html", import.meta.url).href;
  const process = Bun.spawn([
    chrome, "--headless", "--disable-gpu", "--no-sandbox",
    "--allow-file-access-from-files", "--run-all-compositor-stages-before-draw",
    "--virtual-time-budget=3000", "--dump-dom", page,
  ], { stdout: "pipe", stderr: "pipe" });
  const output = await new Response(process.stdout).text();
  expect(await process.exited).toBe(0);
  expect(output).toContain('data-svg-namespace="http://www.w3.org/2000/svg"');
  expect(output).toContain('data-shape-namespace="http://www.w3.org/2000/svg"');
  expect(output).toContain('data-shape-width="80"');
  expect(output).toContain('data-a11y="namespace-contract-title namespace-contract-description"');
  expect(output).toContain('data-clip="url(#namespace-contract-clip)"');
});
