// GENERATED by generate-oss-licenses.ts from bun.lock's production dependency closure
// and installed package metadata. Do not edit manually; run bun run build.
export type OssLicense = { name: string; version: string; license: string; projectUrl: string };
export const ossLicenseProvenance = "bun.lock production dependency closure + installed package metadata";
export const ossLicenses: readonly OssLicense[] = [
  {
    "name": "@floating-ui/core",
    "version": "1.8.0",
    "license": "MIT",
    "projectUrl": "https://floating-ui.com"
  },
  {
    "name": "@floating-ui/dom",
    "version": "1.8.0",
    "license": "MIT",
    "projectUrl": "https://floating-ui.com"
  },
  {
    "name": "@floating-ui/react",
    "version": "0.27.20",
    "license": "MIT",
    "projectUrl": "https://floating-ui.com/docs/react"
  },
  {
    "name": "@floating-ui/react-dom",
    "version": "2.1.9",
    "license": "MIT",
    "projectUrl": "https://floating-ui.com/docs/react-dom"
  },
  {
    "name": "@floating-ui/utils",
    "version": "0.2.12",
    "license": "MIT",
    "projectUrl": "https://floating-ui.com"
  },
  {
    "name": "@fontsource/ibm-plex-mono",
    "version": "5.3.0",
    "license": "OFL-1.1",
    "projectUrl": "https://fontsource.org/fonts/ibm-plex-mono"
  },
  {
    "name": "@fontsource/ibm-plex-sans-kr",
    "version": "5.3.0",
    "license": "OFL-1.1",
    "projectUrl": "https://fontsource.org/fonts/ibm-plex-sans-kr"
  },
  {
    "name": "@mantine/core",
    "version": "9.4.1",
    "license": "MIT",
    "projectUrl": "https://mantine.dev/"
  },
  {
    "name": "@mantine/hooks",
    "version": "9.4.1",
    "license": "MIT",
    "projectUrl": "https://mantine.dev"
  },
  {
    "name": "@types/debug",
    "version": "4.1.13",
    "license": "MIT",
    "projectUrl": "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/debug"
  },
  {
    "name": "@types/estree",
    "version": "1.0.9",
    "license": "MIT",
    "projectUrl": "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/estree"
  },
  {
    "name": "@types/estree-jsx",
    "version": "1.0.5",
    "license": "MIT",
    "projectUrl": "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/estree-jsx"
  },
  {
    "name": "@types/hast",
    "version": "3.0.5",
    "license": "MIT",
    "projectUrl": "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/hast"
  },
  {
    "name": "@types/mdast",
    "version": "4.0.4",
    "license": "MIT",
    "projectUrl": "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mdast"
  },
  {
    "name": "@types/ms",
    "version": "2.1.0",
    "license": "MIT",
    "projectUrl": "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ms"
  },
  {
    "name": "@types/unist",
    "version": "3.0.3",
    "license": "MIT",
    "projectUrl": "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/unist"
  },
  {
    "name": "acorn",
    "version": "8.17.0",
    "license": "MIT",
    "projectUrl": "https://github.com/acornjs/acorn"
  },
  {
    "name": "acorn-jsx",
    "version": "5.3.2",
    "license": "MIT",
    "projectUrl": "https://github.com/acornjs/acorn-jsx"
  },
  {
    "name": "bail",
    "version": "2.0.2",
    "license": "MIT",
    "projectUrl": "https://github.com/wooorm/bail"
  },
  {
    "name": "ccount",
    "version": "2.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/wooorm/ccount"
  },
  {
    "name": "character-entities",
    "version": "2.0.2",
    "license": "MIT",
    "projectUrl": "https://github.com/wooorm/character-entities"
  },
  {
    "name": "character-entities-html4",
    "version": "2.1.0",
    "license": "MIT",
    "projectUrl": "https://github.com/wooorm/character-entities-html4"
  },
  {
    "name": "character-entities-legacy",
    "version": "3.0.0",
    "license": "MIT",
    "projectUrl": "https://github.com/wooorm/character-entities-legacy"
  },
  {
    "name": "character-reference-invalid",
    "version": "2.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/wooorm/character-reference-invalid"
  },
  {
    "name": "clsx",
    "version": "2.1.1",
    "license": "MIT",
    "projectUrl": "https://github.com/lukeed/clsx"
  },
  {
    "name": "debug",
    "version": "4.4.3",
    "license": "MIT",
    "projectUrl": "git://github.com/debug-js/debug"
  },
  {
    "name": "decode-named-character-reference",
    "version": "1.3.0",
    "license": "MIT",
    "projectUrl": "https://github.com/wooorm/decode-named-character-reference"
  },
  {
    "name": "dequal",
    "version": "2.0.3",
    "license": "MIT",
    "projectUrl": "https://github.com/lukeed/dequal"
  },
  {
    "name": "detect-node-es",
    "version": "1.1.0",
    "license": "MIT",
    "projectUrl": "https://github.com/thekashey/detect-node"
  },
  {
    "name": "devlop",
    "version": "1.1.0",
    "license": "MIT",
    "projectUrl": "https://github.com/wooorm/devlop"
  },
  {
    "name": "escape-string-regexp",
    "version": "5.0.0",
    "license": "MIT",
    "projectUrl": "https://github.com/sindresorhus/escape-string-regexp"
  },
  {
    "name": "estree-util-is-identifier-name",
    "version": "3.0.0",
    "license": "MIT",
    "projectUrl": "https://github.com/syntax-tree/estree-util-is-identifier-name"
  },
  {
    "name": "estree-util-visit",
    "version": "2.0.0",
    "license": "MIT",
    "projectUrl": "https://github.com/syntax-tree/estree-util-visit"
  },
  {
    "name": "extend",
    "version": "3.0.2",
    "license": "MIT",
    "projectUrl": "https://github.com/justmoon/node-extend"
  },
  {
    "name": "get-nonce",
    "version": "1.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/theKashey/get-nonce"
  },
  {
    "name": "htm",
    "version": "3.1.1",
    "license": "Apache-2.0",
    "projectUrl": "https://github.com/developit/htm"
  },
  {
    "name": "is-alphabetical",
    "version": "2.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/wooorm/is-alphabetical"
  },
  {
    "name": "is-alphanumerical",
    "version": "2.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/wooorm/is-alphanumerical"
  },
  {
    "name": "is-decimal",
    "version": "2.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/wooorm/is-decimal"
  },
  {
    "name": "is-hexadecimal",
    "version": "2.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/wooorm/is-hexadecimal"
  },
  {
    "name": "is-plain-obj",
    "version": "4.1.0",
    "license": "MIT",
    "projectUrl": "https://github.com/sindresorhus/is-plain-obj"
  },
  {
    "name": "longest-streak",
    "version": "3.1.0",
    "license": "MIT",
    "projectUrl": "https://github.com/wooorm/longest-streak"
  },
  {
    "name": "markdown-table",
    "version": "3.0.4",
    "license": "MIT",
    "projectUrl": "https://github.com/wooorm/markdown-table"
  },
  {
    "name": "mdast-util-find-and-replace",
    "version": "3.0.2",
    "license": "MIT",
    "projectUrl": "https://github.com/syntax-tree/mdast-util-find-and-replace"
  },
  {
    "name": "mdast-util-from-markdown",
    "version": "2.0.3",
    "license": "MIT",
    "projectUrl": "https://github.com/syntax-tree/mdast-util-from-markdown"
  },
  {
    "name": "mdast-util-gfm",
    "version": "3.1.0",
    "license": "MIT",
    "projectUrl": "https://github.com/syntax-tree/mdast-util-gfm"
  },
  {
    "name": "mdast-util-gfm-autolink-literal",
    "version": "2.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/syntax-tree/mdast-util-gfm-autolink-literal"
  },
  {
    "name": "mdast-util-gfm-footnote",
    "version": "2.1.0",
    "license": "MIT",
    "projectUrl": "https://github.com/syntax-tree/mdast-util-gfm-footnote"
  },
  {
    "name": "mdast-util-gfm-strikethrough",
    "version": "2.0.0",
    "license": "MIT",
    "projectUrl": "https://github.com/syntax-tree/mdast-util-gfm-strikethrough"
  },
  {
    "name": "mdast-util-gfm-table",
    "version": "2.0.0",
    "license": "MIT",
    "projectUrl": "https://github.com/syntax-tree/mdast-util-gfm-table"
  },
  {
    "name": "mdast-util-gfm-task-list-item",
    "version": "2.0.0",
    "license": "MIT",
    "projectUrl": "https://github.com/syntax-tree/mdast-util-gfm-task-list-item"
  },
  {
    "name": "mdast-util-mdx",
    "version": "3.0.0",
    "license": "MIT",
    "projectUrl": "https://github.com/syntax-tree/mdast-util-mdx"
  },
  {
    "name": "mdast-util-mdx-expression",
    "version": "2.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/syntax-tree/mdast-util-mdx-expression"
  },
  {
    "name": "mdast-util-mdx-jsx",
    "version": "3.2.0",
    "license": "MIT",
    "projectUrl": "https://github.com/syntax-tree/mdast-util-mdx-jsx"
  },
  {
    "name": "mdast-util-mdxjs-esm",
    "version": "2.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/syntax-tree/mdast-util-mdxjs-esm"
  },
  {
    "name": "mdast-util-phrasing",
    "version": "4.1.0",
    "license": "MIT",
    "projectUrl": "https://github.com/syntax-tree/mdast-util-phrasing"
  },
  {
    "name": "mdast-util-to-markdown",
    "version": "2.1.2",
    "license": "MIT",
    "projectUrl": "https://github.com/syntax-tree/mdast-util-to-markdown"
  },
  {
    "name": "mdast-util-to-string",
    "version": "4.0.0",
    "license": "MIT",
    "projectUrl": "https://github.com/syntax-tree/mdast-util-to-string"
  },
  {
    "name": "micromark",
    "version": "4.0.2",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark/tree/main/packages/micromark"
  },
  {
    "name": "micromark-core-commonmark",
    "version": "2.0.3",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark/tree/main/packages/micromark-core-commonmark"
  },
  {
    "name": "micromark-extension-gfm",
    "version": "3.0.0",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark-extension-gfm"
  },
  {
    "name": "micromark-extension-gfm-autolink-literal",
    "version": "2.1.0",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark-extension-gfm-autolink-literal"
  },
  {
    "name": "micromark-extension-gfm-footnote",
    "version": "2.1.0",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark-extension-gfm-footnote"
  },
  {
    "name": "micromark-extension-gfm-strikethrough",
    "version": "2.1.0",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark-extension-gfm-strikethrough"
  },
  {
    "name": "micromark-extension-gfm-table",
    "version": "2.1.1",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark-extension-gfm-table"
  },
  {
    "name": "micromark-extension-gfm-tagfilter",
    "version": "2.0.0",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark-extension-gfm-tagfilter"
  },
  {
    "name": "micromark-extension-gfm-task-list-item",
    "version": "2.1.0",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark-extension-gfm-task-list-item"
  },
  {
    "name": "micromark-extension-mdx-expression",
    "version": "3.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark-extension-mdx-expression/tree/main/packages/micromark-extension-mdx-expression"
  },
  {
    "name": "micromark-extension-mdx-jsx",
    "version": "3.0.2",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark-extension-mdx-jsx"
  },
  {
    "name": "micromark-extension-mdx-md",
    "version": "2.0.0",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark-extension-mdx-md"
  },
  {
    "name": "micromark-extension-mdxjs",
    "version": "3.0.0",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark-extension-mdxjs"
  },
  {
    "name": "micromark-extension-mdxjs-esm",
    "version": "3.0.0",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark-extension-mdxjs-esm"
  },
  {
    "name": "micromark-factory-destination",
    "version": "2.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark/tree/main/packages/micromark-factory-destination"
  },
  {
    "name": "micromark-factory-label",
    "version": "2.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark/tree/main/packages/micromark-factory-label"
  },
  {
    "name": "micromark-factory-mdx-expression",
    "version": "2.0.3",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark-extension-mdx-expression/tree/main/packages/micromark-factory-mdx-expression"
  },
  {
    "name": "micromark-factory-space",
    "version": "2.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark/tree/main/packages/micromark-factory-space"
  },
  {
    "name": "micromark-factory-title",
    "version": "2.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark/tree/main/packages/micromark-factory-title"
  },
  {
    "name": "micromark-factory-whitespace",
    "version": "2.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark/tree/main/packages/micromark-factory-whitespace"
  },
  {
    "name": "micromark-util-character",
    "version": "2.1.1",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark/tree/main/packages/micromark-util-character"
  },
  {
    "name": "micromark-util-chunked",
    "version": "2.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark/tree/main/packages/micromark-util-chunked"
  },
  {
    "name": "micromark-util-classify-character",
    "version": "2.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark/tree/main/packages/micromark-util-classify-character"
  },
  {
    "name": "micromark-util-combine-extensions",
    "version": "2.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark/tree/main/packages/micromark-util-combine-extensions"
  },
  {
    "name": "micromark-util-decode-numeric-character-reference",
    "version": "2.0.2",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark/tree/main/packages/micromark-util-decode-numeric-character-reference"
  },
  {
    "name": "micromark-util-decode-string",
    "version": "2.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark/tree/main/packages/micromark-util-decode-string"
  },
  {
    "name": "micromark-util-encode",
    "version": "2.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark/tree/main/packages/micromark-util-encode"
  },
  {
    "name": "micromark-util-events-to-acorn",
    "version": "2.0.3",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark-extension-mdx-expression/tree/main/packages/micromark-util-events-to-acorn"
  },
  {
    "name": "micromark-util-html-tag-name",
    "version": "2.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark/tree/main/packages/micromark-util-html-tag-name"
  },
  {
    "name": "micromark-util-normalize-identifier",
    "version": "2.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark/tree/main/packages/micromark-util-normalize-identifier"
  },
  {
    "name": "micromark-util-resolve-all",
    "version": "2.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark/tree/main/packages/micromark-util-resolve-all"
  },
  {
    "name": "micromark-util-sanitize-uri",
    "version": "2.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark/tree/main/packages/micromark-util-sanitize-uri"
  },
  {
    "name": "micromark-util-subtokenize",
    "version": "2.1.0",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark/tree/main/packages/micromark-util-subtokenize"
  },
  {
    "name": "micromark-util-symbol",
    "version": "2.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark/tree/main/packages/micromark-util-symbol"
  },
  {
    "name": "micromark-util-types",
    "version": "2.0.2",
    "license": "MIT",
    "projectUrl": "https://github.com/micromark/micromark/tree/main/packages/micromark-util-types"
  },
  {
    "name": "ms",
    "version": "2.1.3",
    "license": "MIT",
    "projectUrl": "https://github.com/vercel/ms"
  },
  {
    "name": "parse-entities",
    "version": "4.0.2",
    "license": "MIT",
    "projectUrl": "https://github.com/wooorm/parse-entities"
  },
  {
    "name": "react",
    "version": "19.2.0",
    "license": "MIT",
    "projectUrl": "https://react.dev/"
  },
  {
    "name": "react-dom",
    "version": "19.2.0",
    "license": "MIT",
    "projectUrl": "https://react.dev/"
  },
  {
    "name": "react-number-format",
    "version": "5.4.5",
    "license": "MIT",
    "projectUrl": "https://s-yadav.github.io/react-number-format/docs/intro"
  },
  {
    "name": "react-remove-scroll",
    "version": "2.7.2",
    "license": "MIT",
    "projectUrl": "https://github.com/theKashey/react-remove-scroll"
  },
  {
    "name": "react-remove-scroll-bar",
    "version": "2.3.8",
    "license": "MIT",
    "projectUrl": "https://github.com/theKashey/react-remove-scroll-bar"
  },
  {
    "name": "react-style-singleton",
    "version": "2.2.3",
    "license": "MIT",
    "projectUrl": "https://github.com/theKashey/react-style-singleton#readme"
  },
  {
    "name": "remark-gfm",
    "version": "4.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/remarkjs/remark-gfm"
  },
  {
    "name": "remark-mdx",
    "version": "3.1.1",
    "license": "MIT",
    "projectUrl": "https://mdxjs.com"
  },
  {
    "name": "remark-parse",
    "version": "11.0.0",
    "license": "MIT",
    "projectUrl": "https://remark.js.org"
  },
  {
    "name": "remark-stringify",
    "version": "11.0.0",
    "license": "MIT",
    "projectUrl": "https://remark.js.org"
  },
  {
    "name": "scheduler",
    "version": "0.27.0",
    "license": "MIT",
    "projectUrl": "https://react.dev/"
  },
  {
    "name": "stringify-entities",
    "version": "4.0.4",
    "license": "MIT",
    "projectUrl": "https://github.com/wooorm/stringify-entities"
  },
  {
    "name": "tabbable",
    "version": "6.5.0",
    "license": "MIT",
    "projectUrl": "https://github.com/focus-trap/tabbable#readme"
  },
  {
    "name": "tagged-tag",
    "version": "1.0.0",
    "license": "MIT",
    "projectUrl": "https://github.com/sindresorhus/tagged-tag"
  },
  {
    "name": "trough",
    "version": "2.2.0",
    "license": "MIT",
    "projectUrl": "https://github.com/wooorm/trough"
  },
  {
    "name": "tslib",
    "version": "2.8.1",
    "license": "0BSD",
    "projectUrl": "https://www.typescriptlang.org/"
  },
  {
    "name": "type-fest",
    "version": "5.8.0",
    "license": "(MIT OR CC0-1.0)",
    "projectUrl": "https://github.com/sindresorhus/type-fest"
  },
  {
    "name": "unified",
    "version": "11.0.5",
    "license": "MIT",
    "projectUrl": "https://unifiedjs.com"
  },
  {
    "name": "unist-util-is",
    "version": "6.0.1",
    "license": "MIT",
    "projectUrl": "https://github.com/syntax-tree/unist-util-is"
  },
  {
    "name": "unist-util-position-from-estree",
    "version": "2.0.0",
    "license": "MIT",
    "projectUrl": "https://github.com/syntax-tree/unist-util-position-from-estree"
  },
  {
    "name": "unist-util-stringify-position",
    "version": "4.0.0",
    "license": "MIT",
    "projectUrl": "https://github.com/syntax-tree/unist-util-stringify-position"
  },
  {
    "name": "unist-util-visit",
    "version": "5.1.0",
    "license": "MIT",
    "projectUrl": "https://github.com/syntax-tree/unist-util-visit"
  },
  {
    "name": "unist-util-visit-parents",
    "version": "6.0.2",
    "license": "MIT",
    "projectUrl": "https://github.com/syntax-tree/unist-util-visit-parents"
  },
  {
    "name": "use-callback-ref",
    "version": "1.3.3",
    "license": "MIT",
    "projectUrl": "https://github.com/theKashey/use-callback-ref/"
  },
  {
    "name": "use-sidecar",
    "version": "1.1.3",
    "license": "MIT",
    "projectUrl": "https://github.com/theKashey/use-sidecar"
  },
  {
    "name": "vfile",
    "version": "6.0.3",
    "license": "MIT",
    "projectUrl": "https://github.com/vfile/vfile"
  },
  {
    "name": "vfile-message",
    "version": "4.0.3",
    "license": "MIT",
    "projectUrl": "https://github.com/vfile/vfile-message"
  },
  {
    "name": "zwitch",
    "version": "2.0.4",
    "license": "MIT",
    "projectUrl": "https://github.com/wooorm/zwitch"
  }
];
